/** Delay fijo enviado a Movivendor en do/tx. */
export const MOVIVENDOR_VENTA_DELAY_SECONDS = 20;
export const MOVIVENDOR_VENTA_DELAY_MS = MOVIVENDOR_VENTA_DELAY_SECONDS * 1000;
export const MOVIVENDOR_VENTA_CLIENT_TIMEOUT_MS = MOVIVENDOR_VENTA_DELAY_MS;
